/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/warehouse-select`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/money` | `/money`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/parties` | `/parties`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/create-warehouse` | `/create-warehouse`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/warehouse-select`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/money` | `/money`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/parties` | `/parties`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(onboarding)'}/create-warehouse` | `/create-warehouse`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/warehouse-select${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/verify${`?${string}` | `#${string}` | ''}` | `/verify${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/money${`?${string}` | `#${string}` | ''}` | `/money${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/parties${`?${string}` | `#${string}` | ''}` | `/parties${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${'/(tabs)'}/stock${`?${string}` | `#${string}` | ''}` | `/stock${`?${string}` | `#${string}` | ''}` | `${'/(onboarding)'}/create-warehouse${`?${string}` | `#${string}` | ''}` | `/create-warehouse${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/warehouse-select`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/verify` | `/verify`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/money` | `/money`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/parties` | `/parties`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `${'/(onboarding)'}/create-warehouse` | `/create-warehouse`; params?: Router.UnknownInputParams; };
    }
  }
}
